#!/bin/bash

yarn workspace @redhatinsights/backstage-plugin-firelink export-dynamic
cd plugins/firelink/dist-dynamic
rm *.tgz
npm pack
cd ../../..
rm *.tgz
mv plugins/firelink/dist-dynamic/*.tgz .
shasum -a 256 *.tgz | awk '{print $1}' | xxd -r -p | base64
